steps:
  - name: 'ubuntu'
    args: [ 'echo', 'hello world' ]

  - name: 'gcr.io/cloud-builders/docker'
    secretEnv: [ 'USERNAME', 'ACCESS_TOKEN' ]
    entrypoint: 'bash'
    args: [ '-c', 'docker login --username=$$USERNAME --password=$$ACCESS_TOKEN' ]

  - name: 'gcr.io/cloud-builders/docker'
    secretEnv: [ 'USERNAME' ]
    entrypoint: 'bash'
    args: [ '-c', 'buildx build --progress plain -pull --push --file ./docker/gcc/x86_64-pc-linux-gnu.dockerfile --tag $$USERNAME/gcc:x86_64-pc-linux-gnu /var/empty' ]

availableSecrets:
  secretManager:
    - versionName: projects/55784484652/secrets/docker-hub-username/versions/1
      env: 'USERNAME'

    - versionName: projects/55784484652/secrets/docker-hub-access-token/versions/1
      env: 'ACCESS_TOKEN'
